#!/bin/sh
# Start/stop the nerve daemon.
#
### BEGIN INIT INFO
# Provides:          nerve
# Required-Start:    $network $remote_fs $syslog $time
# Required-Stop:     $network $remote_fs $syslog $time
# Should-Start:      $network $named slapd autofs ypbind nscd nslcd
# Should-Stop:       $network $named slapd autofs ypbind nscd nslcd
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Monitor hardware sensors and upload data.
# Description:       
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DESC="nerve daemon"
NAME=nerve
DAEMON=/usr/bin/nerve
PIDFILE=/var/run/nerve.pid
SCRIPTNAME=/etc/init.d/"$NAME"
HOSTNAME=`hostname -s`
CONFIG=/etc/nerve/"$HOSTNAME"

if [ ! -f "$DAEMON" ]; then
    echo "No daemon found: $DAEMON"
    exit 1
fi

if [ ! -f "$CONFIG" ]; then
    echo "No config: $CONFIG"
    exit 1
fi

# Load the config.
. "$CONFIG"

. /lib/lsb/init-functions

case "$1" in
start)	log_daemon_msg "Starting nerve daemon" "nerve"
        start_daemon -p $PIDFILE -- "$DAEMON" -n $HOSTNAME \
                                              -d $DHT_PIN -t $DHT_TYPE \
                                              -m $MOTION_PIN \
                                              $EXTRA_OPTS
        log_end_msg $?
        ;;
stop)	log_daemon_msg "Stopping nerve daemon" "nerve"
        # Ask for kill politely and wait some time.
        "$DAEMON" -k
        RETVAL=$?
        [ $RETVAL -eq 0 ] && [ -e "$PIDFILE" ] && rm -f $PIDFILE
        log_end_msg $RETVAL
        ;;
restart) log_daemon_msg "Restarting nerve daemon" "nerve"
        $0 stop
        $0 start
        log_end_msg $?
        ;;
reload|force-reload) log_daemon_msg "Reloading configuration files for nerve daemon" "nerve"
        $0 restart
        log_end_msg $?
        ;;
status)
        status_of_proc -p $PIDFILE "$DAEMON" $NAME && exit 0 || exit $?
        ;;
*)      log_action_msg "Usage: /etc/init.d/nerve {start|stop|status|restart|reload|force-reload}"
        exit 2
        ;;
esac
exit 0
